use std::fmt;

/// Strongly typed event type enumeration matching Qt `QEvent::Type`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum EventType {
    None = 0,
    Timer = 1,
    MouseButtonPress = 2,
    MouseButtonRelease = 3,
    MouseButtonDblClick = 4,
    MouseMove = 5,
    KeyPress = 6,
    KeyRelease = 7,
    FocusIn = 8,
    FocusOut = 9,
    Enter = 10,
    Leave = 11,
    Paint = 12,
    Move = 13,
    Resize = 14,
    Create = 15,
    Destroy = 16,
    Show = 17,
    Hide = 18,
    Close = 19,
    Quit = 20,
    ParentChange = 21,
    ThreadChange = 22,
    FocusAboutToChange = 23,
    WindowActivate = 24,
    WindowDeactivate = 25,
    ShowToParent = 26,
    HideToParent = 27,
    Wheel = 31,
    WindowTitleChange = 33,
    WindowIconChange = 34,
    ApplicationWindowIconChange = 35,
    ApplicationFontChange = 36,
    ApplicationLayoutDirectionChange = 37,
    ApplicationPaletteChange = 38,
    PaletteChange = 39,
    Clipboard = 40,
    MetaCall = 43,
    SockAct = 50,
    ShortcutOverride = 51,
    DeferredDelete = 52,
    DragEnter = 60,
    DragMove = 61,
    DragLeave = 62,
    Drop = 63,
    ChildAdded = 68,
    ChildPolished = 69,
    ChildRemoved = 71,
    LayoutRequest = 76,
    UpdateRequest = 77,
    UpdateLater = 78,
    ContextMenu = 82,
    InputMethod = 83,
    TabletMove = 87,
    TabletPress = 92,
    TabletRelease = 93,
    ToolTip = 110,
    WhatsThis = 111,
    StatusTip = 112,
    ActionChanged = 113,
    ActionAdded = 114,
    ActionRemoved = 115,
    Shortcut = 117,
    WhatsThisClicked = 118,
    QueryWhatsThis = 123,
    EnterWhatsThisMode = 124,
    LeaveWhatsThisMode = 125,
    HoverEnter = 127,
    HoverLeave = 128,
    HoverMove = 129,
    ZeroTimerEvent = 154,
    DynamicPropertyChange = 170,
    TabletEnterProximity = 171,
    TabletLeaveProximity = 172,
    CursorChange = 183,
    ToolTipChange = 184,
    TouchBegin = 194,
    TouchUpdate = 195,
    TouchEnd = 196,
    NativeGesture = 197,
    Gesture = 198,
    TouchCancel = 209,
    Expose = 206,
    DpiChanged = 250,
    Pointer = 251,
    User = 1000,
    MaxUser = 65535,
}

impl fmt::Display for EventType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
